/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: s_num_1                                               *
* Dimensions:  3 * 20                                                *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

GUI_CONST_STORAGE unsigned short _acs_num_1[] = {3,20,
  0x0000, 0xAD55, 0x5ACB,
  0x4208, 0xFFFF, 0xC638,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x5ACB, 0xF7BE, 0xCE79,
  0x0000, 0x5ACB, 0x9CF3,
  0x0000, 0x2945, 0x7BCF,
  0x2945, 0xDEFB, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x9CF3, 0xFFFF, 0xCE79,
  0x6B4D, 0xFFFF, 0xCE79,
  0x0000, 0xDEFB, 0x7BCF
};

/*************************** End of file ****************************/
