/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: num_1                                                 *
* Dimensions:  4 * 32                                                *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

GUI_CONST_STORAGE unsigned short _acnum_1[] = {4,32,
  0x0000, 0x4208, 0x6B4D, 0x0000,
  0x0000, 0xAD55, 0xFFFF, 0x8C51,
  0x0000, 0xF7BE, 0xFFFF, 0xF7BE,
  0x7BCF, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x5ACB, 0xF7BE, 0xFFFF, 0xFFFF,
  0x0000, 0x5ACB, 0xF7BE, 0xFFFF,
  0x0000, 0x0000, 0x5ACB, 0x8C51,
  0x0000, 0x0000, 0x0000, 0x2945,
  0x0000, 0x0000, 0xB596, 0xDEFB,
  0x0000, 0xB596, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x9CF3, 0xFFFF, 0xFFFF, 0xFFFF,
  0x4208, 0xFFFF, 0xFFFF, 0xFFFF,
  0x0000, 0xCE79, 0xFFFF, 0xCE79,
  0x0000, 0x8C51, 0xCE79, 0x2945
};

/*************************** End of file ****************************/
